//EXAMPLE ON DEFAULT CONSTRUCTER FOR INTILIZING SAME DATA(STATIC MODE)
public class EX2								//MAIN METHOD
{
	public static void main(String[]args)
	{
		BOOKS b1=new BOOKS();					//CREATING AN OBJECT AAND ASSIGNING A REFERENCE TO OBJECT
		b1.showInfo();							//CALLING A METHOD FROM ANOTHER CLASS
	}
}