//EXAMPLE ON CONSTRUCTER OVER-LOADING
public class HW9												//MAIN METHOD
{
	public static void main(String[]args)
	{
		DATEO d1=new DATEO(1996,04,30,01,15,39);				//CREATING AN OBJECT AND ASSIGNING A REFERENCE TO OBJECT
		d1.showDate();											//CALLING A METHOD FROM ANOTHER CLASS
		d1=new DATEO(1996,04,30,01,15);							//CREATING AN OBJECT AND ASSIGNING A RE-REFERENCE TO OBJECT
		d1.showDate();											//CALLING A METHOD FROM ANOTHER CLASS
		d1=new DATEO(1996,04,30,01);							//CREATING AN OBJECT AND ASSIGNING A RE-REFERENCE TO OBJECT
		d1.showDate();											//CALLING A METHOD FROM ANOTHER CLASS
		d1=new DATEO(1996,04,30);								//CREATING AN OBJECT AND ASSIGNING A RE-REFERENCE TO OBJECT
		d1.showDate();											//CALLING A METHOD FROM ANOTHER CLASS
		d1=new DATEO(1996,04);									//CREATING AN OBJECT AND ASSIGNING A RE-REFERENCE TO OBJECT
		d1.showDate();											//CALLING A METHOD FROM ANOTHER CLASS
		d1=new DATEO(1996);										//CREATING AN OBJECT AND ASSIGNING A RE-REFERENCE TO OBJECT
		d1.showDate();											//CALLING A METHOD FROM ANOTHER CLASS
	}
}